---
title: "IRS SOI Tax by Zip Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE, echo=FALSE}
library(flexdashboard)
library(data.table)
library(magrittr)
library(DT)
library(ggplot2)
library(plotly)
library(shinyWidgets)
library(fst)
library(shinycssloaders)
```



```{r 'load-functions', eval=FALSE, include=FALSE}
## Load your R files
lapply(list.files("./R", full.names = TRUE), source)
```


```{r data, echo=FALSE, include=FALSE}
# Data
irs_app_data <- read_fst("irs_app.fst")
irs_app_data <- setDT(irs_app_data, key = "zipcode")
# cols <- c("year", "zipcode", "post_office_city", "county", "state", "agi_level", "a00100", "a00200", "n00200", "total_tax", "n1", "n2", "numdep", "a01000", "n01000", "a02300", "n02300", "a59660", "a09750","a04470", "n02500", "a18425", "n18425", "a18450", "n18450", "a18500", "n18500", "a19300", "n19300", "a00600", "n00600", "a00300", "n00300")
# irs_app_data <-
#   irs_app_data[, ..cols]
```



```{r eval=FALSE, include=FALSE}
irs <- arrow::read_parquet("irs.parquet")
irs <- setDT(irs)
irs <- clean_soi(irs)

cols <- c("year", "zipcode", "state", "county", "agi_level", "post_office_city", "n1", "a00100", "n1", "total_tax")
d <- irs[, ..cols]
```


```{r echo=FALSE}
# sidebar with shiny start button
fluidPage(fluidRow(
  column(
    1,
    pickerInput(
      "State",
      label = "Choose State",
      choices = unique(irs_app_data$state),
      options = list(`actions-box` = TRUE),
      selected = unique(irs_app_data$state),
      multiple = TRUE
    )
  ),
  column(
    1,
    offset = 1,
    pickerInput(
      "County",
      label = "Choose County",
      choices = NULL,
      options = list(`actions-box` = TRUE),
      selected = sort(unique(irs_app_data$county)),
      multiple = TRUE
    )
  ),
  column(
    1,
    offset = 1,
    pickerInput(
      "City",
      label = "Choose City",
      choices = NULL,
      options = list(`actions-box` = TRUE),
      selected = sort(unique(irs_app_data$post_office_city)),
      multiple = TRUE
    )
  ),
    column(
    1,
    offset = 1,
    pickerInput(
      "Zipcode",
      label = "Choose Zipcode",
      choices = NULL,
      options = list(`actions-box` = TRUE),
      selected = sort(unique(irs_app_data$zipcode)),
      multiple = TRUE
    )
  ),
  column(
    1,
    offset = 1,
    pickerInput(
      "AGI",
      label = "Choose Income",
      choices = unique(irs_app_data$agi_level),
      options = list(`actions-box` = TRUE),
      selected = unique(irs_app_data$agi_level),
      multiple = TRUE
    )
  )
))
```


```{r, echo=FALSE}
state <- reactive({
  irs_app_data[state %chin% input$State]
})

# Adjust County choices based on State selected
observeEvent(state(), {
  choices <- 
    unique(state()$county)
  updatePickerInput(
    session,
    inputId = "County",
    choices = choices,
    selected = sort(choices))
})

county <- reactive({
  state()[county %chin% input$County]
})

# Adjust City choices based on County selected
observeEvent(county(), {
  choices <- unique(county()$post_office_city)
  updatePickerInput(
    session,
    inputId = "City",
    choices = choices,
    selected = sort(choices))
})

city <- reactive({
  county()[post_office_city %chin% input$City]
})

observeEvent(city(), {
  choices <- unique(city()$zipcode)
    #unique(irs_app_data[post_office_city %in% input$City]$zipcode)
  updatePickerInput(
    session,
    inputId = "Zipcode",
    choices = choices,
    selected = sort(choices))
})

df <- reactive({
   d <- irs_app_data[zipcode %chin% input$Zipcode &
                  agi_level %chin% input$AGI]
   return(d)
   })
```


## Column {data-width="500"}

### Annual Summary of Federal Tax Paid by All Reported Zip Codes

```{r summary-table, echo=FALSE}
renderDT({
  # https://taxfoundation.org/federal-tax-revenue-source-1934-2018/
  datatable(
      df()[,
      .(
        tot_agi = sum(as.numeric(a00100), na.rm = TRUE) / 1000000,
        tot_tax = sum(as.numeric(total_tax), na.rm = TRUE) /
          1000000,
        tot_returns = sum(as.numeric(n1), na.rm = TRUE) / 1000000,
        unique_zips = length(unique(zipcode))
      ),
      by = year],
    colnames = c(
      "Year",
      "Total AGI ($B)",
      "Federal Tax ($B)",
      "Total Returns (m)",
      "Unique Zips"
    ),
    options =
      list(
        pageLength = 15,
        scrollY = TRUE,
        dom = 't'
      ),
    rownames = FALSE
  ) %>%
    formatRound(
      columns = c(2:4),
      mark = ",",
      digits = 1
    ) %>%
    formatRound(
      columns = 5,
      mark = ",",
      digits = 0
    )
})
```

## Column {data-width="500"}

### Annual Average Adjusted Gross Income by Income Group

```{r plot-agi, echo=FALSE}
renderPlotly({
  df()[,
    {
      agi_sum = sum(a00100, na.rm = TRUE)
      total = sum(n1, na.rm = TRUE)
      agi_return = agi_sum / total
      list(`Income Amount` = agi_return ,
           `Returns` = total)
    },
    by = .(Year = year,
           `Income Group` = agi_level)][, 
    plot_ly(
      .SD,
      x = ~ Year,
      y = ~ `Income Amount`,
      color =  ~ `Income Group`,
      type = "scatter",
      mode = "lines",
      showlegend = F,
      fill = ~'',
      hoverinfo = 'text',
      text = ~ paste(
        '</br> Year: ',
        Year,
        '</br> After Tax Income: ',
        paste0("$", format(`Income Amount`,
                           digits = 2), "k"),
        '</br> Income Group: ',
        `Income Group`,
        '</br> # of Returns: ',
        format(
          `Returns`,
          big.mark = ",",
          digits = 2,
          scientific = FALSE
        )
      )
    ) %>%
      add_markers(
        size = ~ `Returns`,
        mode = "markers")]
})
```

### Annual Average Federal Tax Rates by Income Group

```{r show-tax-rate, echo=FALSE}
renderPlotly({
  df()[,
  {
    agi_sum = sum(a00100 , na.rm = TRUE)
    tot_tax = sum(total_tax, na.rm = TRUE)
    tax_rate = tot_tax / agi_sum
    total = sum(n1 , na.rm = TRUE)
    list(`Returns` = total,
         `Tax Rate` = tax_rate)
  },
  by = .(Year = year, `Income Group` = agi_level)][, 
  plot_ly(
    .SD,
    x = ~ Year,
    y = ~ `Tax Rate`,
    color =  ~ `Income Group`,
    type = "scatter",
    mode = "lines",
    fill = ~'',
    showlegend = F,
    hoverinfo = 'text',
    text = ~ paste(
      '</br> Year: ',
      Year,
      '</br> Tax Rate: ',
      paste0(format(`Tax Rate` * 100,
                    digits = 2), "%"),
      '</br> Income Group: ',
      `Income Group`,
      '</br> # of Returns: ',
      format(
        `Returns`,
        big.mark = ",",
        digits = 0,
        scientific = FALSE
      )
    )
  ) %>%
    add_markers(size = ~ `Returns`,
                mode = "markers")]
})
```


